@api = https://localhost:5031
@bookId = d9d45ccc-df42-46bf-9f73-b61be1242dfb

### Get book
GET {{api}}/api/books/{{bookId}}

### Get books
GET {{api}}/api/books

### Create new book
POST {{api}}/api/books
content-type: application/json

{
    "title": "Domain-driven design",
    "author": "Eric J. Evans",    
    "cost": 500,
    "inventoryAmount": 20
}